name: Build and test

on:
  push:
    branches:
      - master
      - 'test_mac'
  pull_request:
    branches:
      - master
  
jobs:
  build-n-test:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest]
    runs-on: ${{ matrix.os }}

    services:
      # Label used to access the service container
      mysql:
        # Docker Hub image
        image: mysql:5.7
        # Provide the config for MySQL
        # The database credentials correspond to the config file
        # tests\short\examples\testconfig.json
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: aug_vertebrates
          MYSQL_USER: augustus
          MYSQL_PASSWORD: aug_passwd
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2

    # Install python-mysql-connector
    - name: Install python-mysql-connector
      run: pip3 install mysql-connector-python

    # Install required dependencies
    - name: Install dependencies (Linux)
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      run: sudo ./tests/short/utils/installDependencies.sh

    # Install required dependencies
    - name: Install dependencies (Mac)
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        brew install boost
        brew install zlib
        brew install gsl
        brew install suite-sparse
        brew install lp_solve
        brew install sqlite
        brew install mysql
        brew install mysql++
        brew install bamtools
        brew install samtools
        brew install htslib

    # Build AUGUSTUS
    - name: Build AUGUSTUS
      run: make all

    # Execute unit tests
    - name: Execute unit tests
      if: ${{ matrix.os == 'ubuntu-20.04' }}  #TODO: make working on mac
      run: make unit_test

    # Test AUGUSTUS
    - name: Test AUGUSTUS (examples folder with comparison)
      if: ${{ matrix.os == 'ubuntu-20.04' }}
      run: ./execute_test.py --compare --html --mysql examples
      working-directory: tests/short/

    - name: Test AUGUSTUS (examples folder without comparison on mac)
      if: ${{ matrix.os == 'macos-latest' }}
      run: ./execute_test.py --mysql examples
      working-directory: tests/short/      

    # Test bam2wig
    - name: Test bam2wig
      run: ./execute_test.py --compare --html bam2wig
      working-directory: tests/short/

    # Test bam2hints
    - name: Test bam2hints
      run: ./execute_test.py --compare --html bam2hints
      working-directory: tests/short/

    # Upload html diffs of failed test cases
    - name: Upload HTML diffs
      uses: actions/upload-artifact@v2
      if: ${{ failure() && matrix.os == 'ubuntu-20.04' }}
      with:
        name: html-diffs
        path: tests/short/output_html/

    # Build and publich doxygen documentation (only on push in master)
    - name: Build documentation
      if: ${{ matrix.os == 'ubuntu-20.04' && github.ref == 'refs/heads/master' && github.event_name == 'push' }}
      uses: mattnotmitt/doxygen-action@v1
      with:
        doxyfile-path: 'doxygen.conf'

    - name: Publish documentation of master on gh-pages
      if: ${{ matrix.os == 'ubuntu-20.04' && github.ref == 'refs/heads/master' && github.event_name == 'push' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./doxygen/html/
