# This workflow builds AUGUSTUS and executes the 
# longrunning test cases
name: Execute AUGUSTUS longrunning test cases

on:
  push:
    branches:
      - master
      - 'longrunning_tests'

  #schedule:
  # execute workflow at scheduled time
  #- cron:  '30 1 * * *'

env:
  TOOLDIR: /data/tools

jobs:
  longrunning_test:
    runs-on: [self-hosted, linux, ubuntu]

    steps:
    - name: Check out repository
      uses: actions/checkout@v2


    # Install required python packages
    - name: Install numpy
      run: pip3 install numpy

    - name: Install python wget
      run: pip3 install wget


    - name: Build AUGUSTUS
      run: make all

    # - name: Execute single genome test cases
    #   run: ./test_single.sh -e /data/eval/
    #   working-directory: tests/longrunning/single_genome/

    # - name: Extract desired accuracy values
    #   run: ./extract_accuracy_values.py --path single_genome/output/eval
    #   working-directory: tests/longrunning/

      #TODO: change working-directory to tests/longrunning/cgp/
      #TODO: pass eval path as argument
      #TODO: use same code for accuracy value extraction as for single genome test case
    - name: Execute cgp test case
#      run: python3 executeTestCGP.py --chunks 27 30 47 54 57 80 86 101 118 --run --eval
      run: python3 executeTestCGP.py --chunks 27 --run --eval
      working-directory: scripts/
