name: Build and test

on:
  push:
    branches:
      - 'test_mac'

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v2

    # Install required dependencies
    - name: Install dependencies
      run: |
        brew install boost
        brew install zlib
        brew install gsl
        brew install suite-sparse
        brew install lp_solve
        brew install sqlite
        brew install mysql
        brew install mysql++
        brew install bamtools
        brew install samtools
        brew install htslib

    # Build AUGUSTUS
    - name: Build AUGUSTUS
      run: make all

    # Execute unit tests
    - name: Execute unit tests
      run: make unit_test

    # Test AUGUSTUS
    - name: Test AUGUSTUS (examples folder)
      run: ./execute_test.py examples
      working-directory: tests/short/

    # Test bam2wig
    - name: Test bam2wig
      run: ./execute_test.py --compare --html bam2wig
      working-directory: tests/short/

    # Test bam2hints
    - name: Test bam2hints
      run: ./execute_test.py --compare --html bam2hints
      working-directory: tests/short/
